### ISSUE TITLE
Bunch of errors

### ISSUE THREAD

**Issue by AnnikaNoren** [learn-co-curriculum/dsc-convolutional-neural-networks-codealong#1]
There are many errors that occur during the codealong.  

Here are screenshots of two of them:
![Screen Shot 2020-03-06 at 9 45 27 AM](https://user-images.githubusercontent.com/10696260/76093610-4624cb80-5f8f-11ea-81ae-dcdce56fc239.png)
![Screen Shot 2020-03-06 at 9 45 39 AM](https://user-images.githubusercontent.com/10696260/76093622-4c1aac80-5f8f-11ea-9866-0a225eb9a03a.png)

**Comment by jessepisel** [comment]
Thanks for opening this issue @AnnikaNoren :wave:. The first issue when you run the cell `os.mkdir(new_dir)` it is creating an error since that directory already exists in your file structure. To start fresh, remove the directory named `'split/'` and run the cell again. 

As for the second error, if you run a cell with `! pip install pillow` and run the import cell again that should solve the issue.

I am closing this issue at this time.
